# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

# branches to build
branches:
  # whitelist
  only:
    - master

# build version format
version: "{build}"

# Get the latest stable version of Node 0.STABLE.latest
install:
  - ps: Install-Product node 0.10.30 x86
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - cmd: npm install -g bower gulp
  - cmd: bower i
  - cmd: gulp build
  - cmd: npm test
